### ISSUE TITLE
Discontinued GeoLite legacy database

### ISSUE THREAD

**Issue by naoki-maeda** [CounterpartyXCP/counterblock#172]
Maxmind has discontinued it's GeoLite legacy database.
https://blog.maxmind.com/2018/01/02/discontinuation-of-the-geolite-legacy-databases/

We might use Geolite 2. However, the format of the file has been changed to "mmdb".
https://dev.maxmind.com/geoip/geoip2/geolite2/

Should we consider another way?

**Comment by cryptcoin-junkey** [comment]
It looks CSV versionS also downloadable. But the better way is to use https://pypi.org/project/geoip2/ , IMO.

**Comment by naoki-maeda** [comment]
Thank you!!!
I will use geoip2.
