### ISSUE TITLE
Modularizing Counterblockd to use a plugin framework

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterblock#24]
I use Counterblockd as for a certain API methods, and because it's convenient to have only one daemon querying counterpartyd for new messsages every 3 seconds. On the other hand I don't use any of the database tables except for my own. I'm sure there are also cases where someone may want betting.py but not enhanced_asset info and trade updates or vice versa. If it's not overly ambitious I think it would be a great improvement.

**Comment by robby-dermody** [comment]
This was done in counterblock 1.2.x
