### ISSUE TITLE
README should mention use of python2?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterblock#67]
No mention of the version of python used is bizarre, not to mention the discrepancy between counterpartyd (python3) and this (python2) repository (i realize why) makes me consider this harmful (there should at least be a mild explanation in the README as https://github.com/CounterpartyXCP/counterblockd/pull/64 has done, I think).
##

**Comment by robby-dermody** [comment]
resolved as move to python3 complete
