### ISSUE TITLE
Numerous warnings for malformed enhanced external info

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterblock#90]
A user with `counterblockd` problem reported that he spotted many warnings during `counterblockd` DB reparse about a malformed JSON feed..
Maybe some throttling could be added somewhere in `counterblockd` (counter for repeated messages?) or downstream?

**Comment by robby-dermody** [comment]
there is throttling already built in, but we could tweak it further

**Comment by robby-dermody** [comment]
for example, see https://github.com/CounterpartyXCP/counterblock/blob/master/counterblock/lib/components/assets.py#L201
